spring.application.name=examen

server.port=8015

spring.datasource.url=jdbc:h2:mem:examenjava;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# Consola H2 (http://localhost:8015/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datos iniciales
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql