-- Password: admin123 (SHA-256 Base64)
INSERT INTO USUARIO (LOGIN, PASSWORD, NOMBRE, CLIENTE, EMAIL, FECHAALTA, STATUS, INTENTOS, FECHAMODIFICACION, FECHA_VIGENCIA, APELLIDO_PATERNO, APELLIDO_MATERNO, AREA)
VALUES ('admin', 'MjQwYmU1MThmYWJkMjcyNGRkYjZmMDRlZWIxZGE1OTY3NDQ4ZDdlODMxYzA4YzhmYTgyMjgwOWY3NGM3MjBhOQo=', 'Administrador', 1.0, 'admin@empresa.com', CURRENT_DATE, 'A', 0, CURRENT_DATE, DATE '2026-12-31', 'Sistema', 'General', 1);

INSERT INTO USUARIO (LOGIN, PASSWORD, NOMBRE, CLIENTE, EMAIL, FECHAALTA, STATUS, INTENTOS, FECHAMODIFICACION, FECHA_VIGENCIA, APELLIDO_PATERNO, APELLIDO_MATERNO, AREA)
VALUES ('usuario1', 'MjQwYmU1MThmYWJkMjcyNGRkYjZmMDRlZWIxZGE1OTY3NDQ4ZDdlODMxYzA4YzhmYTgyMjgwOWY3NGM3MjBhOQo=', 'Juan', 1.0, 'juan@empresa.com', CURRENT_DATE, 'A', 0, CURRENT_DATE, DATE '2026-12-31', 'Perez', 'Lopez', 2);

INSERT INTO USUARIO (LOGIN, PASSWORD, NOMBRE, CLIENTE, EMAIL, FECHAALTA, STATUS, INTENTOS, FECHAMODIFICACION, FECHA_VIGENCIA, APELLIDO_PATERNO, APELLIDO_MATERNO, AREA)
VALUES ('usuario2', 'MjQwYmU1MThmYWJkMjcyNGRkYjZmMDRlZWIxZGE1OTY3NDQ4ZDdlODMxYzA4YzhmYTgyMjgwOWY3NGM3MjBhOQo=', 'Maria', 1.0, 'maria@empresa.com', CURRENT_DATE, 'B', 0, CURRENT_DATE, DATE '2026-12-31', 'Garcia', 'Rodriguez', 3);

INSERT INTO USUARIO (LOGIN, PASSWORD, NOMBRE, CLIENTE, EMAIL, FECHAALTA, STATUS, INTENTOS, FECHAMODIFICACION, FECHA_VIGENCIA, APELLIDO_PATERNO, APELLIDO_MATERNO, AREA)
VALUES ('usuario3', 'MjQwYmU1MThmYWJkMjcyNGRkYjZmMDRlZWIxZGE1OTY3NDQ4ZDdlODMxYzA4YzhmYTgyMjgwOWY3NGM3MjBhOQo=', 'Carlos', 1.0, 'carlos@empresa.com', CURRENT_DATE, 'R', 0, CURRENT_DATE, DATE '2026-06-30', 'Sanchez', 'Morales', 4);
