CREATE TABLE IF NOT EXISTS USUARIO (
    LOGIN VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CLIENTE DOUBLE NOT NULL,
    EMAIL VARCHAR(50),
    FECHAALTA DATE NOT NULL,
    FECHABAJA DATE,
    STATUS CHAR(1) NOT NULL DEFAULT 'A',
    INTENTOS DOUBLE NOT NULL DEFAULT 0,
    FECHAREVOCADO DATE,
    FECHA_VIGENCIA DATE,
    NO_ACCESO INTEGER,
    APELLIDO_PATERNO VARCHAR(50),
    APELLIDO_MATERNO VARCHAR(50),
    AREA INTEGER,
    FECHAMODIFICACION DATE NOT NULL,
    PRIMARY KEY (LOGIN)
);
